spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/Documents/h2/db/querydsl
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    properties:
      hibernate.format_sql: true
    hibernate:
      ddl-auto: create

logging:
  level:
    org:
      springframework:
        SQL: debug
      hibernate:
        type:
          descriptor:
            sql: trace
